create table public.audit_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_prompt text null,
  pii_detected jsonb null,
  risk_level text null,
  model_used text null,
  response_toxicity double precision null,
  execution_id character varying not null,
  constraint audit_logs_pkey primary key (id)
) TABLESPACE pg_default;
